---

- name: Clear cache
  shell: "{{symfony_console}} cache:clear --no-debug"
  args:
    chdir: "{{ symfony_current_release_dir }}"
  become_user: "{{ www_user }}"
  become: yes

- name: Live switch
  file:
    src: "{{ symfony_current_release_dir }}"
    dest: "{{ symfony_current_dir }}"
    state: link
